// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreatePostData, CreatePostResponses, DeleteMediaData, DeleteMediaErrors, DeleteMediaResponses, GetFilteredPostsData, GetFilteredPostsResponses, GetPostByIdData, GetPostByIdErrors, GetPostByIdResponses, GetPostBySlugData, GetPostBySlugErrors, GetPostBySlugResponses, GetSectionsData, GetSectionsResponses, GetTagsData, GetTagsResponses, GetUserFilteredPostsData, GetUserFilteredPostsResponses, PurgePostData, PurgePostErrors, PurgePostResponses, UpdatePostData, UpdatePostErrors, UpdatePostResponses, UploadMediaData, UploadMediaErrors, UploadMediaResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class PostControllerService {
    /**
     * Get user's filtered posts
     *
     * Returns a paginated list of the authenticated user's posts filtered by parameters, including deleted and published status.
     */
    public static getUserFilteredPosts<ThrowOnError extends boolean = false>(options?: Options<GetUserFilteredPostsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUserFilteredPostsResponses, unknown, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/post',
            ...options
        });
    }
    
    /**
     * Create a new post
     *
     * Creates a new post for the authenticated user and returns the created post data.
     */
    public static createPost<ThrowOnError extends boolean = false>(options?: Options<CreatePostData, ThrowOnError>) {
        return (options?.client ?? client).post<CreatePostResponses, unknown, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/post',
            ...options
        });
    }
    
    /**
     * Update a post
     *
     * Updates an existing post with the provided data. Only authenticated users can update their own posts.
     */
    public static updatePost<ThrowOnError extends boolean = false>(options: Options<UpdatePostData, ThrowOnError>) {
        return (options.client ?? client).put<UpdatePostResponses, UpdatePostErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/post',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get post by ID
     *
     * Retrieves a post by its unique identifier (UUID) for authenticated users.
     */
    public static getPostById<ThrowOnError extends boolean = false>(options: Options<GetPostByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetPostByIdResponses, GetPostByIdErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/post/{id}',
            ...options
        });
    }
    
    /**
     * Get filtered public posts
     *
     * Returns a paginated list of public posts filtered by the provided parameters. Requires authentication.
     */
    public static getFilteredPosts<ThrowOnError extends boolean = false>(options?: Options<GetFilteredPostsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetFilteredPostsResponses, unknown, ThrowOnError>({ url: '/api/v1/post/public', ...options });
    }
    
    /**
     * Get public post by slug
     *
     * Retrieves a public post using its slug. This endpoint is accessible without authentication.
     */
    public static getPostBySlug<ThrowOnError extends boolean = false>(options: Options<GetPostBySlugData, ThrowOnError>) {
        return (options.client ?? client).get<GetPostBySlugResponses, GetPostBySlugErrors, ThrowOnError>({ url: '/api/v1/post/public/{slug}', ...options });
    }
    
    /**
     * Get all tags
     *
     * Retrieves the complete list of tags available in the system.
     */
    public static getTags<ThrowOnError extends boolean = false>(options?: Options<GetTagsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetTagsResponses, unknown, ThrowOnError>({ url: '/api/v1/post/public/tag', ...options });
    }
    
    /**
     * Get all sections
     *
     * Retrieves the complete list of sections available in the system.
     */
    public static getSections<ThrowOnError extends boolean = false>(options?: Options<GetSectionsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetSectionsResponses, unknown, ThrowOnError>({ url: '/api/v1/post/public/section', ...options });
    }
    
    /**
     * Permanently delete a post
     *
     * Permanently deletes a post by its unique identifier (UUID). Only authenticated users can perform this action.
     */
    public static purgePost<ThrowOnError extends boolean = false>(options: Options<PurgePostData, ThrowOnError>) {
        return (options.client ?? client).delete<PurgePostResponses, PurgePostErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/post/purge/{id}',
            ...options
        });
    }
}

export class MediaControllerService {
    /**
     * Upload media file to a post
     *
     * Uploads a media file (image, video, etc.) to the specified post. Only authenticated users can upload files.
     */
    public static uploadMedia<ThrowOnError extends boolean = false>(options: Options<UploadMediaData, ThrowOnError>) {
        return (options.client ?? client).post<UploadMediaResponses, UploadMediaErrors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/media/{postId}',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    /**
     * Delete media file from a post
     *
     * Deletes a media file from the specified post. Only authenticated users can delete files.
     */
    public static deleteMedia<ThrowOnError extends boolean = false>(options: Options<DeleteMediaData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteMediaResponses, DeleteMediaErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/media/{postId}/{fileName}',
            ...options
        });
    }
}
