// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://wah1d-backend.onrender.com' | (string & {});
};

/**
 * Standard error response used throughout the API.
 */
export type ErrorDTO = {
    /**
     * HTTP status code of the error
     */
    status: number;
    /**
     * Date and time when the error occurred
     */
    timestamp: string;
    /**
     * Indicates if the operation was successful (always false in case of error)
     */
    success: boolean;
    /**
     * Descriptive error message
     */
    message: string;
};

/**
 * Arbitrary JSON content
 */
export type JsonNode = string | number | boolean | null | JsonNode[] | { [key: string]: JsonNode };

/**
 * Block of content within a post, such as text, image, or other media.
 */
export type PostBlockDTO = {
    /**
     * Unique identifier of the content block.
     */
    id: number;
    /**
     * Position of the block in the post.
     */
    position: number;
    /**
     * Type of the content block (e.g., text, image, code).
     */
    type: string;
    content: JsonNode;
};

/**
 * Request object for updating an existing blog post.
 */
export type UpdatePostReq = {
    /**
     * Unique identifier of the post to update.
     */
    id: string;
    /**
     * New title for the post.
     */
    title?: string | null;
    /**
     * New description for the post.
     */
    description?: string | null;
    /**
     * Updated content blocks for the post.
     */
    content?: Array<PostBlockDTO> | null;
    /**
     * Updated set of cover image URLs.
     */
    covers?: Array<string | null> | null;
    /**
     * Updated section.
     */
    section?: string | null;
    /**
     * Updated set of tag names.
     */
    tags?: Array<string | null> | null;
    /**
     * Updated slug for the post.
     */
    slug?: string | null;
    /**
     * Whether the post should be published.
     */
    published?: boolean | null;
    /**
     * Whether the post should be marked as deleted.
     */
    deleted?: boolean | null;
};

/**
 * Data transfer object representing a blog post.
 */
export type PostDTO = {
    /**
     * Unique identifier of the post.
     */
    id: string;
    /**
     * Title of the post.
     */
    title: string;
    /**
     * Date and time when the post was created.
     */
    createdAt: string;
    /**
     * Set of cover image URLs for the post.
     */
    covers: Array<string>;
    /**
     * Short description of the post.
     */
    description: string;
    /**
     * Section of the post.
     */
    section?: string;
    /**
     * Set of tags associated with the post.
     */
    tags: Array<string>;
    /**
     * List of content blocks for the post.
     */
    content: Array<PostBlockDTO>;
    /**
     * Slug (URL-friendly identifier) for the post.
     */
    slug?: string | null;
    /**
     * Indicates if the post is deleted.
     */
    deleted: boolean;
    /**
     * Indicates if the post is published.
     */
    published: boolean;
};

export type PagePostDetails = {
    totalElements?: number;
    totalPages?: number;
    pageable?: PageableObject;
    numberOfElements?: number;
    first?: boolean;
    last?: boolean;
    size?: number;
    content?: Array<PostDetails>;
    number?: number;
    sort?: Array<SortObject>;
    empty?: boolean;
};

export type PageableObject = {
    unpaged?: boolean;
    pageNumber?: number;
    paged?: boolean;
    pageSize?: number;
    offset?: number;
    sort?: Array<SortObject>;
};

/**
 * Detailed information about a blog post, including status and publication details.
 */
export type PostDetails = {
    /**
     * Unique identifier of the post.
     */
    id: string;
    /**
     * Title of the post.
     */
    title: string;
    /**
     * Date and time when the post was created.
     */
    createdAt: string;
    /**
     * Set of cover image URLs for the post.
     */
    covers: Array<string>;
    /**
     * Short description of the post.
     */
    description: string;
    /**
     * Section of the post.
     */
    section?: string;
    /**
     * Set of tags associated with the post.
     */
    tags: Array<string>;
    /**
     * Slug (URL-friendly identifier) for the post.
     */
    slug?: string | null;
    /**
     * Indicates if the post is deleted.
     */
    deleted: boolean;
    /**
     * Indicates if the post is published.
     */
    published: boolean;
    /**
     * Date and time when the post was published.
     */
    publishedAt?: string | null;
};

export type SortObject = {
    direction?: string;
    nullHandling?: string;
    ascending?: boolean;
    property?: string;
    ignoreCase?: boolean;
};

export type GetUserFilteredPostsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
        query?: string;
        sections?: Array<string>;
        tags?: Array<string>;
        from?: string;
        to?: string;
        deleted?: boolean;
        published?: boolean;
    };
    url: '/api/v1/post';
};

export type GetUserFilteredPostsErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorDTO;
};

export type GetUserFilteredPostsError = GetUserFilteredPostsErrors[keyof GetUserFilteredPostsErrors];

export type GetUserFilteredPostsResponses = {
    /**
     * Successfully retrieved user's filtered posts.
     */
    200: PagePostDetails;
};

export type GetUserFilteredPostsResponse = GetUserFilteredPostsResponses[keyof GetUserFilteredPostsResponses];

export type CreatePostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/post';
};

export type CreatePostErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorDTO;
};

export type CreatePostError = CreatePostErrors[keyof CreatePostErrors];

export type CreatePostResponses = {
    /**
     * Successfully created the post.
     */
    200: PostDTO;
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type UpdatePostData = {
    body: UpdatePostReq;
    path?: never;
    query?: never;
    url: '/api/v1/post';
};

export type UpdatePostErrors = {
    /**
     * Post not found.
     */
    404: PostDTO;
    /**
     * Internal Server Error
     */
    500: ErrorDTO;
};

export type UpdatePostError = UpdatePostErrors[keyof UpdatePostErrors];

export type UpdatePostResponses = {
    /**
     * Successfully updated the post.
     */
    200: PostDTO;
};

export type UpdatePostResponse = UpdatePostResponses[keyof UpdatePostResponses];

export type UploadMediaData = {
    body?: {
        /**
         * Media file to upload
         */
        file: Blob | File;
    };
    path: {
        /**
         * UUID of the post to which the file will be attached
         */
        postId: string;
    };
    query?: never;
    url: '/api/v1/media/{postId}';
};

export type UploadMediaErrors = {
    /**
     * Invalid file or post ID.
     */
    400: string;
    /**
     * Unauthorized.
     */
    401: string;
    /**
     * Post not found.
     */
    404: string;
    /**
     * Internal Server Error
     */
    500: ErrorDTO;
};

export type UploadMediaError = UploadMediaErrors[keyof UploadMediaErrors];

export type UploadMediaResponses = {
    /**
     * File uploaded successfully.
     */
    200: string;
};

export type UploadMediaResponse = UploadMediaResponses[keyof UploadMediaResponses];

export type GetPostByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/post/{id}';
};

export type GetPostByIdErrors = {
    /**
     * Post not found.
     */
    404: PostDTO;
    /**
     * Internal Server Error
     */
    500: ErrorDTO;
};

export type GetPostByIdError = GetPostByIdErrors[keyof GetPostByIdErrors];

export type GetPostByIdResponses = {
    /**
     * Successfully retrieved the post.
     */
    200: PostDTO;
};

export type GetPostByIdResponse = GetPostByIdResponses[keyof GetPostByIdResponses];

export type GetFilteredPostsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
        query?: string;
        sections?: Array<string>;
        tags?: Array<string>;
        from?: string;
        to?: string;
    };
    url: '/api/v1/post/public';
};

export type GetFilteredPostsErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorDTO;
};

export type GetFilteredPostsError = GetFilteredPostsErrors[keyof GetFilteredPostsErrors];

export type GetFilteredPostsResponses = {
    /**
     * Successfully retrieved filtered public posts.
     */
    200: PagePostDetails;
};

export type GetFilteredPostsResponse = GetFilteredPostsResponses[keyof GetFilteredPostsResponses];

export type GetPostBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/post/public/{slug}';
};

export type GetPostBySlugErrors = {
    /**
     * Post not found.
     */
    404: PostDTO;
    /**
     * Internal Server Error
     */
    500: ErrorDTO;
};

export type GetPostBySlugError = GetPostBySlugErrors[keyof GetPostBySlugErrors];

export type GetPostBySlugResponses = {
    /**
     * Successfully retrieved the public post.
     */
    200: PostDTO;
};

export type GetPostBySlugResponse = GetPostBySlugResponses[keyof GetPostBySlugResponses];

export type GetTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/post/public/tag';
};

export type GetTagsErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorDTO;
};

export type GetTagsError = GetTagsErrors[keyof GetTagsErrors];

export type GetTagsResponses = {
    /**
     * Successfully retrieved the list of tags.
     */
    200: Array<string>;
};

export type GetTagsResponse = GetTagsResponses[keyof GetTagsResponses];

export type GetSectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/post/public/section';
};

export type GetSectionsErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorDTO;
};

export type GetSectionsError = GetSectionsErrors[keyof GetSectionsErrors];

export type GetSectionsResponses = {
    /**
     * Successfully retrieved the list of sections.
     */
    200: Array<string>;
};

export type GetSectionsResponse = GetSectionsResponses[keyof GetSectionsResponses];

export type PurgePostData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/post/purge/{id}';
};

export type PurgePostErrors = {
    /**
     * Post not found.
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: ErrorDTO;
};

export type PurgePostError = PurgePostErrors[keyof PurgePostErrors];

export type PurgePostResponses = {
    /**
     * Successfully deleted the post.
     */
    200: unknown;
};

export type DeleteMediaData = {
    body?: never;
    path: {
        /**
         * UUID of the post from which the file will be deleted
         */
        postId: string;
        /**
         * Name of the file to delete
         */
        fileName: string;
    };
    query?: never;
    url: '/api/v1/media/{postId}/{fileName}';
};

export type DeleteMediaErrors = {
    /**
     * Invalid file name or post ID.
     */
    400: unknown;
    /**
     * Unauthorized.
     */
    401: unknown;
    /**
     * Post or file not found.
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: ErrorDTO;
};

export type DeleteMediaError = DeleteMediaErrors[keyof DeleteMediaErrors];

export type DeleteMediaResponses = {
    /**
     * File deleted successfully.
     */
    200: unknown;
};
