POSTGRES_DB={{.POSTGRES_DB}}
POSTGRES_USER={{.POSTGRES_USER}}
POSTGRES_PASSWORD={{.POSTGRES_PASSWORD}}

SPRING_DATASOURCE_URL={{.SPRING_DATASOURCE_URL}}
SPRING_DATASOURCE_USERNAME={{.SPRING_DATASOURCE_USERNAME}}
SPRING_DATASOURCE_PASSWORD={{.SPRING_DATASOURCE_PASSWORD}}

PORT={{.PORT}}

SUPABASE_ISSUER_URI={{.SUPABASE_ISSUER_URI}}
SUPABASE_JWKS_URI={{.SUPABASE_JWKS_URI}}
SUPABASE_URL={{.SUPABASE_URL}}
SUPABASE_KEY={{.SUPABASE_KEY}}

API_URL={{.API_URL}}
FRONTEND_URL={{.FRONTEND_URL}}